const stageNames={ceiling_door:'01 天花板上的第二扇门',wall_reel_phone:'02 墙纸里的卷线轮',dinner_clamp:'03 多摆的一副碗筷',table_strikes:'04 听筒被夺走以后',likeness_cutter:'05 像他的剪影室',red_tether:'06 拴住门外人的绳',ten_minute_sun:'07 十分钟太阳饭厅',resonant_ceiling:'08 安静会砸下来',winter_frame:'09 门框从四边合拢'};
const plainRule={ceiling_door:'等第三声结束；门板必须真的砸到地面。',wall_reel_phone:'等第七码归零；卷线轮必须真实收到底。',dinner_clamp:'钥匙声出现；两半饭桌必须真实合拢。',table_strikes:'三次撞击完成；凸轮必须到第三击状态。',likeness_cutter:'照片第三次睁眼；剪影机必须完成一次真实切除。',red_tether:'钥匙转满一圈；卷盘必须完成一次拖拽。',ten_minute_sun:'亮砂流尽；配重轴必须让饭桌翻面。',resonant_ceiling:'五秒安静后的第一声出现；对应板必须真实坠落。',winter_frame:'霜线到门槛；四边门框必须完成一次压合。'};
const escapeHtml=value=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
async function loadGuide(){
  const [tests,branches]=await Promise.all([fetch('../data/chapter-one-prophecy-state-tests-v3.json').then(r=>r.json()),fetch('../data/chapter-one-damage-branches-v3.json').then(r=>r.json())]);
  document.querySelector('#walkthrough-list').innerHTML=tests.entries.map((entry,index)=>`<section class="walk-stage panel"><div class="stage-number">${stageNames[entry.beatId]||entry.beatId}</div><h3>${escapeHtml(entry.prophecy)}</h3><p><strong>什么时候算完成：</strong>${plainRule[entry.beatId]}</p><p><strong>不操作会怎样：</strong>机构照常完成，默认把本关碎片留在最危险的位置或状态。</p><details ${index===0?'open':''}><summary>展开 8 条已测试路线</summary><ol>${entry.positive.map(trace=>`<li>${escapeHtml(trace.designDescription)}</li>`).join('')}</ol><p class="novel"><strong>额外盲测：</strong>${escapeHtml(entry.novelNinth.designDescription)}——它不在八条样本中，但同样通过。</p></details></section>`).join('')+`<section class="walk-stage panel"><div class="stage-number">10 没有内容的答案盒</div><h3>中心槽不会吐出隐藏真相</h3><p>保住至少三种碎片，走到答案盒；先体验任意一个碎片中心假结局，再返回盒前，选择“中心保持空白”，输入自己的句子。</p></section>`;
  document.querySelector('#branch-list').innerHTML=branches.interStageBranches.map((group,index)=>`<section class="branch-group panel"><h3>${index+1}. ${escapeHtml(group.transition)}</h3><p>${escapeHtml(group.selectionMoment)}</p><div class="branch-options">${group.branches.map(branch=>`<article><b>${escapeHtml(branch.nextVariant)}</b><small>${escapeHtml(branch.keyChoice)}</small></article>`).join('')}</div></section>`).join('');
}
loadGuide().catch(error=>{document.querySelector('#walkthrough-list').innerHTML=`<p class="warning">攻略数据读取失败：${escapeHtml(error.message)}。请刷新页面。</p>`});
